"""创建models表

Revision ID: 10eacf8a2bca
Revises: 7a44400de9af
Create Date: 2026-07-09 20:33:03.008150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10eacf8a2bca'
down_revision: Union[str, Sequence[str], None] = '7a44400de9af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('name', sa.String(length=100), nullable=False, comment='模型显示名称'),
    sa.Column('model_id', sa.String(length=100), nullable=False, comment='模型标识符，如 gpt-4'),
    sa.Column('provider_id', sa.BigInteger(), nullable=False, comment='所属供应商ID'),
    sa.Column('capabilities', sa.String(length=500), nullable=True, comment='能力标签，逗号分隔: function_call,vision,streaming'),
    sa.Column('context_length', sa.Integer(), nullable=False, comment='上下文窗口大小'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: available/unavailable/rate_limited'),
    sa.Column('input_price', sa.Numeric(precision=10, scale=6), nullable=False, comment='输入价格（每1K tokens）'),
    sa.Column('output_price', sa.Numeric(precision=10, scale=6), nullable=False, comment='输出价格（每1K tokens）'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='货币单位'),
    sa.Column('is_default', sa.Boolean(), nullable=False, comment='是否为默认模型'),
    sa.Column('description', sa.Text(), nullable=True, comment='模型描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['provider_id'], ['model_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('models')
    # ### end Alembic commands ###
