"""创建agent表

Revision ID: 530561e8bd51
Revises: a792a9a136c6
Create Date: 2026-07-12 09:46:29.268354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530561e8bd51'
down_revision: Union[str, Sequence[str], None] = 'a792a9a136c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Agent 名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='类型: conversation/tool/analysis/creative/workflow'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: active/inactive/error/draft'),
    sa.Column('model_id', sa.BigInteger(), nullable=True, comment='关联的模型ID'),
    sa.Column('config', sa.JSON(), nullable=True, comment='Agent 完整配置'),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='成功率 %'),
    sa.Column('call_count_7d', sa.Integer(), nullable=False, comment='近7天调用次数'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='当前版本号'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_versions',
    sa.Column('agent_id', sa.BigInteger(), nullable=False, comment='所属 Agent ID'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本号'),
    sa.Column('config', sa.JSON(), nullable=True, comment='该版本的配置快照'),
    sa.Column('changelog', sa.String(length=500), nullable=True, comment='变更说明'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='是否为当前版本'),
    sa.Column('published_by', sa.String(length=100), nullable=True, comment='发布者'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agent_versions')
    op.drop_table('agents')
    # ### end Alembic commands ###
