"""创建model_providers表

Revision ID: 7a44400de9af
Revises: d331acd2dc14
Create Date: 2026-07-09 20:01:30.316914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a44400de9af'
down_revision: Union[str, Sequence[str], None] = 'd331acd2dc14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_providers',
    sa.Column('name', sa.String(length=100), nullable=False, comment='供应商名称'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='供应商类型: openai/anthropic/aliyun/azure/local/custom'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='连接状态: connected/disconnected/error'),
    sa.Column('endpoint', sa.String(length=500), nullable=False, comment='API端点地址'),
    sa.Column('api_key', sa.Text(), nullable=True, comment='API密钥（加密存储）'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='供应商描述'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_providers')
    # ### end Alembic commands ###
