"""创建tools表

Revision ID: a792a9a136c6
Revises: a9f8af7a44f7
Create Date: 2026-07-12 09:35:54.412877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a792a9a136c6'
down_revision: Union[str, Sequence[str], None] = 'a9f8af7a44f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tools',
    sa.Column('name', sa.String(length=200), nullable=False, comment='工具名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='工具描述'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='工具类型: builtin/http_api/custom_function'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: enabled/disabled/error'),
    sa.Column('config', sa.JSON(), nullable=True, comment='工具配置（因类型而异）'),
    sa.Column('function_definition', sa.JSON(), nullable=True, comment='Function Calling 定义（OpenAI 格式）'),
    sa.Column('call_count_7d', sa.Integer(), nullable=False, comment='近7天调用次数'),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='成功率 %'),
    sa.Column('avg_latency', sa.Integer(), nullable=False, comment='平均延迟 ms'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tools')
    # ### end Alembic commands ###
