"""创建prompts和prompt_versions表

Revision ID: b826117cb8e9
Revises: 10eacf8a2bca
Create Date: 2026-07-10 19:29:26.268446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b826117cb8e9'
down_revision: Union[str, Sequence[str], None] = '10eacf8a2bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Prompt 名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='分类'),
    sa.Column('tags', sa.JSON(), nullable=True, comment='标签列表，JSON 数组'),
    sa.Column('content', sa.Text(), nullable=False, comment='Prompt 正文内容'),
    sa.Column('variables', sa.JSON(), nullable=True, comment='变量定义，JSON 数组'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='当前版本号'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='状态: draft/published'),
    sa.Column('created_by', sa.String(length=100), nullable=True, comment='创建者'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_versions',
    sa.Column('prompt_id', sa.BigInteger(), nullable=False, comment='所属 Prompt ID'),
    sa.Column('version', sa.String(length=50), nullable=False, comment='版本号'),
    sa.Column('content', sa.Text(), nullable=False, comment='该版本的内容快照'),
    sa.Column('changelog', sa.String(length=500), nullable=True, comment='变更说明'),
    sa.Column('is_current', sa.Boolean(), nullable=False, comment='是否为当前版本'),
    sa.Column('published_by', sa.String(length=100), nullable=True, comment='发布者'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='发布时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_versions')
    op.drop_table('prompts')
    # ### end Alembic commands ###
