"""知识库新增分段检索配置字段

Revision ID: e3a6ce689a66
Revises: 530561e8bd51
Create Date: 2026-07-12 10:43:39.241319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3a6ce689a66'
down_revision: Union[str, Sequence[str], None] = '530561e8bd51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('minio_path', sa.String(length=1000), nullable=True, comment='MinIO 存储路径'))
    op.add_column('documents', sa.Column('processed_at', sa.DateTime(), nullable=True, comment='处理完成时间'))
    op.drop_column('documents', 'file_path')
    op.add_column('knowledge_bases', sa.Column('chunk_method', sa.String(length=20), nullable=False, comment='分段方式: fixed/sentence/paragraph'))
    op.add_column('knowledge_bases', sa.Column('chunk_size', sa.Integer(), nullable=False, comment='分段大小（tokens）'))
    op.add_column('knowledge_bases', sa.Column('chunk_overlap', sa.Integer(), nullable=False, comment='重叠大小（tokens）'))
    op.add_column('knowledge_bases', sa.Column('retrieval_strategy', sa.String(length=20), nullable=False, comment='检索策略: vector/fulltext/hybrid'))
    op.add_column('knowledge_bases', sa.Column('top_k', sa.Integer(), nullable=False, comment='返回结果数'))
    op.add_column('knowledge_bases', sa.Column('similarity_threshold', sa.Float(), nullable=False, comment='相似度阈值'))
    op.drop_column('segments', 'keywords')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('segments', sa.Column('keywords', mysql.JSON(), nullable=True, comment='关键词列表'))
    op.drop_column('knowledge_bases', 'similarity_threshold')
    op.drop_column('knowledge_bases', 'top_k')
    op.drop_column('knowledge_bases', 'retrieval_strategy')
    op.drop_column('knowledge_bases', 'chunk_overlap')
    op.drop_column('knowledge_bases', 'chunk_size')
    op.drop_column('knowledge_bases', 'chunk_method')
    op.add_column('documents', sa.Column('file_path', mysql.VARCHAR(length=1000), nullable=True, comment='MinIO 存储路径'))
    op.drop_column('documents', 'processed_at')
    op.drop_column('documents', 'minio_path')
    # ### end Alembic commands ###
